//
//  NSStringTransform+Heteronym.swift
//  SIMChat
//
//  Created by sagesse on 2/24/16.
//  Copyright © 2016 sagesse. All rights reserved.
//

import Foundation

public func NSStringTransformOfHeteronyms(string: NSString, _ range: NSRange?, _ transform: CFString, _ reverse: Bool) -> NSArray {
    let convert = { (value: String) -> String in
        let ms = NSMutableString(string: value)
        CFStringTransform(ms, nil, transform, reverse)
        return ms as String
    }
    guard transform == kCFStringTransformToLatin else {
        return [convert(string as String)]
    }
    return (0 ..< string.length).reduce((NSMutableArray(), 0)) {
        let ch = string.substringWithRange(NSMakeRange($1, 1)) as String
        if let ms = _heteronyms[ch] {
            if $0.1 < $1 {
                $0.0.addObject(convert(string.substringWithRange(NSMakeRange($0.1, $1 - $0.1))))
            }
            $0.0.addObject(ms)
            return ($0.0, $1 + 1)
        }
        if $1 + 1 == string.length {
            $0.0.addObject(convert(string.substringWithRange(NSMakeRange($0.1, $1 - $0.1 + 1))))
        }
        return ($0.0, $0.1)
    }.0
}

private let _heteronyms = [
    "阿": ["ā", "ē"],
    "挨": ["āi", "ái"],
    "拗": ["ào", "niǜ"],
    "扒": ["bā", "pá"],
    "把": ["bǎ", "bà"],
    "蚌": ["bàng", "bèng"],
    "薄": ["báo", "bó"],
    "堡": ["bǎo", "bǔ", "pù"],
    "暴": ["bào", "pù"],
    "背": ["bèi", "bēi"],
    "奔": ["bēn", "bèn"],
    "臂": ["bì", "bei"],
    "辟": ["bì", "pì"],
    "扁": ["biǎn", "piān"],
    "便": ["biàn", "pián"],
    "骠": ["biāo", "piào"],
    "屏": ["píng", "bǐng"],
    "剥": ["bō", "bāo"],
    "泊": ["bó", "pō"],
    "伯": ["bó", "bǎi"],
    "簸": ["bǒ", "bò"],
    "膊": ["bó", "bo"],
    "卜": ["bo", "bǔ"],
    "藏": ["cáng", "zàng"],
    "差": ["chā", "chà", "cī"],
    "禅": ["chán", "shàn"],
    "颤": ["chàn", "zhàn"],
    "场": ["chǎng", "cháng"],
    "嘲": ["cháo", "zhāo"],
    "车": ["chē", "jū"],
    "称": ["chèng", "chēng"],
    "澄": ["chéng", "dèng"],
    "匙": ["chí", "shi"],
    "冲": ["chōng", "chòng"],
    "臭": ["chòu", "xiù"],
    "处": ["chǔ", "chù"],
    "畜": ["chù", "xù"],
    "创": ["chuàng", "chuāng"],
    "绰": ["chuò", "chāo"],
    "伺": ["cì", "sì"],
    "枞": ["cōng", "zōng"],
    "攒": ["cuán", "zǎn"],
    "撮": ["cuō", "zuǒ"],
    "综": ["zèng", "zōng"],
    "钻": ["zuān", "zuàn"],
    "柞": ["zuò", "zhà"],
    "作": ["zuō", "zuo"],
    "答": ["dá", "dā"],
    "大": ["dà", "dài"],
    "逮": ["dài", "dǎi"],
    "单": ["dán", "chán", "shàn"],
    "当": ["dāng", "dàng"],
    "倒": ["dǎo", "dào"],
    "提": ["dī", "tí"],
    "得": ["dé", "de", "děi"],
    "的": ["dí", "dì", "de"],
    "都": ["dōu", "dū"],
    "掇": ["duō", "duo"],
    "度": ["duó", "dù"],
    "囤": ["dùn", "tún"],
    "发": ["fà", "fā"],
    "坊": ["fāng", "fáng"],
    "分": ["fēn", "fèn"],
    "缝": ["féng", "fèng"],
    "服": ["fú", "fù"],
    "杆": ["gān", "gǎn"],
    "葛": ["gé", "gě"],
    "革": ["gé", "jí"],
    "合": ["gě", "hé"],
    "给": ["gěi", "jǐ"],
    "更": ["gēng", "gèng"],
    "颈": ["jǐng", "gěng"],
    "供": ["gōng", "gòng"],
    "枸": ["gǒu", "gōu", "jǔ"],
    "估": ["gū", "gù"],
    "骨": ["gū", "gǔ"],
    "谷": ["gǔ", "yù"],
    "冠": ["guān", "guàn"],
    "桧": ["guì", "huì"],
    "过": ["guō", "guò"],
    "虾": ["há", "xiā"],
    "哈": ["hǎ", "hà", "hā"],
    "汗": ["hán", "hàn"],
    "巷": ["hàng", "xiàng"],
    "吭": ["háng", "kēng"],
    "号": ["háo", "hào"],
    "和": ["hé", "hè", "hú", "huó", "huò", "huo"],
    "貉": ["hé", "háo"],
    "喝": ["hē", "hè"],
    "横": ["héng", "hèng"],
    "虹": ["hóng", "jiàng"],
    "划": ["huá", "huà"],
    "晃": ["huǎng", "huàng"],
    "会": ["huì", "kuàì"],
    "混": ["hún", "hùn"],
    "哄": ["hǒng", "hòng"],
    "豁": ["huō", "huò"],
    "奇": ["jī", "qí"],
    "缉": ["jī", "qī"],
    "几": ["jī", "jǐ"],
    "济": ["jǐ", "jì"],
    "纪": ["jǐ", "jì"],
    "偈": ["jì", "jié"],
    "系": ["jì", "xì"],
    "茄": ["jiā", "qié"],
    "夹": ["jiā", "jiá"],
    "假": ["jiǎ", "jià"],
    "间": ["jiān", "jiàn"],
    "将": ["jiāng", "jiàng"],
    "嚼": ["jiáo", "jué"],
    "侥": ["jiǎo", "yáo"],
    "角": ["jiǎo", "jué"],
    "脚": ["jiǎo", "jué"],
    "剿": ["jiǎo", "chāo"],
    "教": ["jiāo", "jiào"],
    "校": ["jiào", "xiào"],
    "解": ["jiě", "jiè", "xiè"],
    "结": ["jiē", "jié"],
    "芥": ["jiè", "gài"],
    "藉": ["jiè", "jí"],
    "矜": ["jīn", "qín"],
    "仅": ["jǐn", "jìn"],
    "劲": ["jìn", "jìng"],
    "龟": ["jūn", "guī", "qiū"],
    "咀": ["jǔ", "zuǐ"],
    "矩": ["jǔ", "ju"],
    "菌": ["jūn", "jùn"],
    "卡": ["kǎ", "qiǎ"],
    "看": ["kān", "kàn"],
    "坷": ["kē", "kě"],
    "壳": ["ké", "qià"],
    "可": ["kě", "kè"],
    "克": ["kè", "kēi"],
    "空": ["kōng", "kòng"],
    "溃": ["kuì", "kui"],
    "蓝": ["lán", "lan"],
    "烙": ["lào", "luò"],
    "勒": ["lè", "lēi"],
    "擂": ["léi", "lèi"],
    "累": ["lèi", "léi", "lěi"],
    "蠡": ["lí", "lǐ"],
    "俩": ["liǎ", "liǎng"],
    "量": ["liáng", "liàng", "liang"],
    "踉": ["liáng", "liàng"],
    "潦": ["liáo", "lǎo"],
    "淋": ["lín", "lìn"],
    "馏": ["liú", "liù"],
    "镏": ["liú", "liù"],
    "碌": ["liù", "lù"],
    "笼": ["lóng", "lǒng"],
    "偻": ["ló", "lǚ"],
    "露": ["lù", "lòu"],
    "捋": ["lǚ", "luō"],
    "绿": ["lǜ", "lù"],
    "络": ["luò", "lào"],
    "落": ["luò", "lào", "là"],
    "脉": ["mò", "mài"],
    "埋": ["mái", "mán"],
    "蔓": ["màn", "wàn"],
    "氓": ["máng", "méng"],
    "蒙": ["méng", "méng", "měng"],
    "眯": ["mí", "mī"],
    "靡": ["mí", "mǐ"],
    "秘": ["bì", "mì", "bèi"],
    "泌": ["mì", "bì"],
    "模": ["mó", "mú"],
    "摩": ["mó", "mā"],
    "缪": ["móu", "miù", "miào"],
    "难": ["nán", "nàn"],
    "宁": ["níng", "nìng"],
    "弄": ["nòng", "lòng"],
    "疟": ["nüè", "yào"],
    "娜": ["nuó", "nà"],
    "排": ["pái", "pǎi"],
    "迫": ["pǎi", "pò"],
    "胖": ["pán", "pàng"],
    "刨": ["páo", "bào"],
    "炮": ["páo", "pào"],
    "喷": ["pēn", "pèn", "pen"],
    "片": ["piàn", "piān"],
    "缥": ["piāo", "piǎo"],
    "撇": ["piē", "piě"],
    "仆": ["pū", "pú"],
    "朴": ["pǔ", "pō", "pò", "piáo"],
    "瀑": ["pù", "bào"],
    "曝": ["pù", "bào"],
    "栖": ["qī", "xī"],
    "蹊": ["qī", "xī"],
    "稽": ["qí", "jī"],
    "荨": ["qián", "xún"],
    "欠": ["qiàn", "qian"],
    "镪": ["qiāng", "qiǎng"],
    "强": ["qiáng", "qiǎng", "jiàng"],
    "悄": ["qiāo", "qiǎo"],
    "翘": ["qiào", "qiáo"],
    "切": ["qiē", "qiè"],
    "趄": ["qiè", "qie", "jū"],
    "亲": ["qīn", "qìng"],
    "曲": ["qū", "qǔ"],
    "雀": ["qùe", "qiao", "qiao"],
    "任": ["rén", "rèn"],
    "散": ["sǎn", "san", "sàn"],
    "丧": ["sāng", "sàng", "sang"],
    "色": ["sè", "shǎi"],
    "塞": ["sè", "sāi", "sài"],
    "煞": ["shā", "shà"],
    "厦": ["shà", "xià"],
    "杉": ["shān", "shā"],
    "苫": ["shàn", "shān"],
    "折": ["shé", "shē", "shé"],
    "舍": ["shě", "shè"],
    "什": ["shén", "shí"],
    "葚": ["shèn", "rèn"],
    "识": ["shí", "zhì"],
    "似": ["shì", "sì"],
    "螫": ["shì", "zhē"],
    "说": ["shuì", "shuō"],
    "数": ["shuò", "shǔ", "shù"],
    "遂": ["suí", "suì"],
    "缩": ["suō", "sù"],
    "沓": ["tà", "ta"],
    "苔": ["tái", "tāi"],
    "调": ["tiáo", "diào"],
    "帖": ["tiē", "ti"],
    "瓦": ["wǎ", "wà"],
    "圩": ["wéi", "xū"],
    "委": ["wēi", "wěi"],
    "尾": ["wěi", "yǐ"],
    "尉": ["wèi", "yù"],
    "乌": ["wū", "wù"],
    "吓": ["xiā", "hè"],
    "鲜": ["xiān", "xiǎn"],
    "纤": ["xiān", "qiàn"],
    "相": ["xiāng", "xiàng"],
    "行": ["xíng", "háng", "hàng", "héng"],
    "省": ["xǐng", "shěng"],
    "宿": ["xiù", "xiǔ", "sù"],
    "削": ["xuē", "xiāo"],
    "血": ["xuè", "xiě"],
    "熏": ["xūn", "xùn"],
    "哑": ["yā", "yǎ"],
    "殷": ["yān", "yīn", "yǐn"],
    "咽": ["yān", "yàn", "yè"],
    "钥": ["yào", "yuè"],
    "叶": ["yè", "xié"],
    "艾": ["yì", "ài"],
    "应": ["yīng", "yìng"],
    "佣": ["yōng", "yòng"],
    "熨": ["yù", "yùn"],
    "与": ["yǔ", "yù"],
    "吁": ["yù", "yū", "xū"],
    "晕": ["yūn", "yùn"],
    "载": ["zǎi", "zài"],
    "择": ["zé", "zhái"],
    "扎": ["zhá", "zhā", "zā"],
    "轧": ["zhá", "yà"],
    "粘": ["zhān", "nián"],
    "涨": ["zhǎng", "zhàng"],
    "着": ["zháo", "zhuó", "zhāo"],
    "正": ["zhēng", "zhèng"],
    "殖": ["zhí", "shi"],
    "中": ["zhōng", "zhòng"],
    "种": ["zhǒng", "zhòng"],
    "轴": ["zhóu", "zhòu"],
    "属": ["zhǔ", "shǔ"],
    "著": ["zhù", "zhe", "zhúo"],
    "转": ["zhuǎn", "zhuàn"],
    "幢": ["zhuàng", "chuáng"]
]
